apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-setup
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/apps/authelia-setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  force: true  # Force recreation of jobs
  dependsOn:
    - name: vault-transit-config
    - name: external-secrets-config
    - name: lldap-setup
    - name: postgres-setup
    - name: istio-config  # For postgres cluster to be ready