apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-setup
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/apps/cert-manager-setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  force: true  # Force recreation of jobs
  dependsOn:
    - name: vault-transit-config
    - name: external-secrets-config
    - name: cert-manager
  postBuild:
    substituteFrom:
      - kind: Secret
        name: vault-admin-token