apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lldap-setup.yaml
  - lldap.yaml
  - authelia-setup.yaml
  - authelia.yaml
  - harbor-setup.yaml
  - harbor.yaml
  - stremio-setup.yaml
  - stremio.yaml
  - plex-setup.yaml
  - plex.yaml
  - nextcloud-setup.yaml
  - nextcloud.yaml
  - vllm.yaml
  - openwebui.yaml