apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lldap-setup
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/apps/lldap-setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  force: true  # Force recreation of jobs
  dependsOn:
    - name: vault
    - name: external-secrets-config
  postBuild:
    substitute:
      vault_admin_token: "${vault_admin_token}"
    substituteFrom:
      - kind: Secret
        name: vault-admin-token