apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap-setup
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./charts/app-setup
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: vault-transit-config
      namespace: flux-system
    - name: external-secrets-config
      namespace: flux-system
  values:
    appName: lldap
    vault:
      secrets:
        - path: lldap
          data:
            LLDAP_JWT_SECRET: "__GENERATE_BASE64__"
            LLDAP_LDAP_USER_PASS: "__GENERATE_BASE64__"