apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-setup
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: flux-system
  suspend: true
  chart:
    spec:
      chart: ./clusters/homelab/charts/app-setup
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: vault
      namespace: flux-system
    - name: external-secrets
      namespace: flux-system
    - name: cloudnative-pg
      namespace: flux-system
  values:
    appName: nextcloud
    vault:
      secrets:
        - path: nextcloud/admin
          data:
            username: "admin"
            password: "__GENERATE_PASSWORD__"
        - path: nextcloud/database
          data:
            name: "nextcloud"
            user: "nextcloud"
            password: "__GENERATE_PASSWORD__"
            host: "postgres-apps-rw.postgres.svc.cluster.local"
            port: "5432"
        - path: nextcloud/ldap
          data:
            bindDN: "uid=nextcloud,ou=people,dc=daddyshome,dc=fr"
            password: "__GENERATE_PASSWORD__"
        - path: nextcloud/smtp
          data:
            host: "smtp.gmail.com"
            port: "587"
            secure: "tls"
            username: "REPLACE_WITH_EMAIL"
            password: "REPLACE_WITH_APP_PASSWORD"
            from: "noreply@daddyshome.fr"
    postgres:
      enabled: true
      database: nextcloud
      username: nextcloud