apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-setup
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: flux-system
  suspend: true
  chart:
    spec:
      chart: ./clusters/homelab/charts/app-setup
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: vault
      namespace: flux-system
    - name: external-secrets
      namespace: flux-system
  values:
    appName: plex
    vault:
      secrets:
        - path: plex/config
          data:
            claim: "claim-ABC123REPLACEME"
            timezone: "Europe/Paris"