apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-nfs-backups
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-vms