apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=PLACEHOLDER_ACCESS_KEY
    aws_secret_access_key=PLACEHOLDER_SECRET_KEY