controller:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

webhook:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

volumeSnapshotClasses:
  - name: csi-rbdplugin-snapclass
    driver: rook-ceph.rbd.csi.ceph.com
    deletionPolicy: Delete
  - name: csi-cephfsplugin-snapclass
    driver: rook-ceph.cephfs.csi.ceph.com
    deletionPolicy: Delete