apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: velero-credentials-vault
  namespace: velero
spec:
  type: kv-v2
  mount: secret
  path: velero
  vaultAuthRef: vault-auth-velero
  destination:
    name: velero-credentials
    create: true
    type: Opaque
    transformation:
      excludes:
        - .*
      templates:
        cloud:
          text: |
            [default]
            aws_access_key_id={{ .Secrets.aws_access_key_id }}
            aws_secret_access_key={{ .Secrets.aws_secret_access_key }}
  refreshAfter: 30s