apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 30m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: velero-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
  
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: secret/data/velero
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: secret/data/velero
      property: aws_secret_access_key