apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-admin-sa.yaml
  - vault-setup-job.yaml
  - postgres-admin-sa.yaml
  - postgres-external-secret.yaml
  - nextcloud-db-external-secret.yaml
  - database-setup-job.yaml