apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nextcloud-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/data/nextcloud/database