apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
  - postgres-superuser-eso.yaml
  - argo-postgres-config-eso.yaml
  - argo-vault-populate-job.yaml
  - argo-db-init-job.yaml
  - workflow-template-vault-populate.yaml
  - ingress.yaml
  - persistence-config.yaml