apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-workflows-workflow-controller-configmap
  namespace: argo-workflows
data:
  # Enable persistence after PostgreSQL is ready
  persistence: |
    archive: true
    archiveTTL: 7d
    postgresql:
      host: postgres-apps-rw.postgres.svc.cluster.local
      port: 5432
      database: argo_workflows
      tableName: argo_workflows
      userNameSecret:
        name: argo-postgres-config
        key: username
      passwordSecret:
        name: argo-postgres-config
        key: password