apiVersion: v1
kind: Secret
metadata:
  name: vault-transit-token
  namespace: vault
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "flux-system"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
  token: "${vault_transit_token}"
