apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lldap
  namespace: lldap
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-ovh-webhook"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/auth-tls-secret: "haproxy-controller/client-ca-cert"
    haproxy.org/auth-tls-verify-client: "required"
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - lldap.${EXTERNAL_DOMAIN}
    secretName: lldap-tls
  rules:
  - host: lldap.${EXTERNAL_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lldap
            port:
              number: 17170
