{{- if .Values.postgres.enabled }}
---
# ExternalSecret for postgres superuser credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgres.superuserSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-setup.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: {{ .Values.postgres.superuserSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      
  data:
  - secretKey: username
    remoteRef:
      key: secret/postgres
      property: POSTGRES_USER
  - secretKey: password
    remoteRef:
      key: secret/postgres
      property: POSTGRES_PASSWORD
{{- end }}