apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: stremio
data:
  buildkitd.toml: |
    [registry."harbor-registry.harbor.svc.cluster.local:5000"]
      insecure = true
    [registry."192.168.1.220:5000"]
      insecure = true