apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
      - name: buildkitd
        image: moby/buildkit:latest
        args:
        - --addr
        - tcp://0.0.0.0:1234
        - --config=/etc/buildkit/buildkitd.toml
        securityContext:
          privileged: true
        ports:
        - containerPort: 1234
          name: buildkit
        volumeMounts:
        - name: config
          mountPath: /etc/buildkit
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: buildkitd-config