apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry-user
  namespace: stremio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-registry-user
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/harbor/registry-user