apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stremio

resources:
  - namespace.yaml
  - service-account.yaml
  - harbor-registry-external-secret.yaml
  - buildkitd-config.yaml
  - buildkitd-deployment.yaml
  - buildkitd-service.yaml
  - build-job.yaml