qm create 100 \
  --name "talos-cp-1" \
  --balloon 0 \
  --bios ovmf \
  --boot "order=ide2;scsi0;net0" \
  --cores 2 \
  --cpu host \
  --efidisk0 local-lvm:4,efitype=4m \
  --ide2 local:iso/talos-nocloud-amd64.iso,media=cdrom \
  --machine q35 \
  --memory 12288 \
  --net0 virtio,bridge=vmbr0,firewall=1 \
  --numa 0 \
  --onboot 1 \
  --ostype l26 \
  --scsi0 local-lvm:32,backup=0,cache=writethrough,discard=on,iothread=1,replicate=0 \
  --scsihw virtio-scsi-single \
  --sockets 1 \
  --vga std

qm create 101 \
  --name "talos-wk-1-gpu" \
  --balloon 0 \
  --bios ovmf \
  --boot "order=ide2;scsi0;net0" \
  --cores 12 \
  --cpu host \
  --efidisk0 local-lvm:4,efitype=4m \
  --ide2 local:iso/talos-nocloud-amd64.iso,media=cdrom \
  --hostpci0 0000:01:00,pcie=1 \
  --machine q35 \
  --memory 48128 \
  --net0 virtio,bridge=vmbr0,firewall=1 \
  --numa 0 \
  --onboot 1 \
  --ostype l26 \
  --scsi0 local-lvm:128,backup=0,cache=writethrough,discard=on,iothread=1,replicate=0 \
  --scsi1 local-lvm:800,backup=0,cache=writethrough,discard=on,iothread=1,replicate=0 \
  --scsihw virtio-scsi-single \
  --sockets 1 \
  --vga std

qm create 102 \
  --name "talos-wk-2" \
  --balloon 0 \
  --bios ovmf \
  --boot "order=ide2;scsi0;net0" \
  --cores 10 \
  --cpu host \
  --efidisk0 local-lvm:4,efitype=4m \
  --ide2 local:iso/talos-nocloud-amd64.iso,media=cdrom \
  --machine q35 \
  --memory 37888 \
  --net0 virtio,bridge=vmbr0,firewall=1 \
  --numa 0 \
  --onboot 1 \
  --ostype l26 \
  --scsi0 local-lvm:96,backup=0,cache=writethrough,discard=on,iothread=1,replicate=0 \
  --scsi1 local-lvm:640,backup=0,cache=writethrough,discard=on,iothread=1,replicate=0 \
  --scsihw virtio-scsi-single \
  --sockets 1 \
  --vga std
