name: vault-config
namespace: vault
syncWave: "-14"  # Deploy after Vault (-16) and ESO (-15)
project: core
path: manifests/core/vault-config
dependsOn:
  - name: vault
    namespace: argocd
  - name: external-secrets-operator
    namespace: argocd
  - name: argo-workflows-crds
    namespace: argocd