apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: PLACEHOLDER
spec:
  refreshInterval: 15m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: postgres-superuser
    creationPolicy: Owner
    deletionPolicy: Retain
  
  data:
  - secretKey: username
    remoteRef:
      key: secret/data/postgres/superuser
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/postgres/superuser
      property: password