apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-superuser
  namespace: PLACEHOLDER
spec:
  type: kv-v2
  mount: secret
  path: postgres/superuser
  destination:
    name: postgres-superuser
    create: true
    overwrite: true
    type: Opaque
  vaultAuthRef: PLACEHOLDER-auth