name: cilium
project: core
namespace: kube-system
path: manifests/core/cilium
plugin: argocd-envsubst-plugin
autoSync: "true"
prune: "true"
syncWave: "-30"
createNamespace: "false"  # kube-system already exists
serverSideApply: "true"  # Required for Talos Linux
