apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.18.1
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.talos.yaml

patches:
  - path: patch-hubble-ui-nginx.yaml
    target:
      kind: ConfigMap
      name: hubble-ui-nginx
      namespace: kube-system
