apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ovh-webhook
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@daddyshome.fr
    privateKeySecretRef:
      name: letsencrypt-ovh-webhook-account
    solvers:
    - dns01:
        webhook:
          groupName: acme.daddyshome.fr
          solverName: ovh
          config:
            endpoint: ovh-eu
            # All credentials are read from the ovh-credentials secret
            applicationKeyRef:
              key: applicationKey
              name: ovh-credentials
            applicationSecretRef:
              key: applicationSecret
              name: ovh-credentials
            consumerKeyRef:
              key: consumerKey  
              name: ovh-credentials