# Use Vault Secrets Operator to manage OVH credentials
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cert-manager
    serviceAccount: cert-manager
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  type: kv-v2
  mount: secret
  path: ovh-dns
  destination:
    name: ovh-credentials
    create: true
    type: Opaque
  refreshAfter: 30s
  vaultAuthRef: cert-manager
  rolloutRestartTargets:
    - kind: Deployment
      name: cert-manager
    - kind: Deployment
      name: cert-manager-webhook