apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  refreshInterval: 30m
  
  secretStoreRef:
    name: nas-vault-backend
    kind: ClusterSecretStore
  
  target:
    name: ovh-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  
  # Fetch all keys from ovh-dns path
  dataFrom:
  - extract:
      key: secret/data/ovh-dns