apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - device-plugin-config.yaml
  - fix-nvidia-persistenced.yaml
  - fix-nvidia-runtime.yaml
  - gpu-feature-discovery.yaml
  - nvidia-device-plugin.yaml
  - nvidia-runtime-class.yaml