apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/infrastructure/controllers
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  resources:
    - external-secrets-operator.yaml
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: flux-system