apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  targetNamespace: haproxy-ingress
  interval: 10m
  chart:
    spec:
      chart: haproxy-ingress
      version: v0.14.7
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      kind: DaemonSet
      ingressClassResource:
        name: haproxy
        enabled: true
        default: true
        controllerValue: haproxy.github.io/ingress-controller
      service:
        type: NodePort
        externalTrafficPolicy: Local
        nodePorts:
          http: 30080
          https: 30443
      config:
        ssl-redirect: "true"
        ssl-ciphers: "ECDHE+AESGCM:ECDHE+AES256:ECDHE+AES128:!DHE:!RSA:!AES128:!AESCCM"
        ssl-cipher-suites: "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"
        ssl-options: "no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets"
        hsts: "true"
        hsts-max-age: "31536000"
        hsts-include-subdomains: "true"
        hsts-preload: "true"
      hostNetwork: false
      watchIngressWithoutClass: true