apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-tls-setup
  namespace: lldap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lldap
  name: istio-tls-setup
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-tls-setup-cross-namespace
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["client-ca-cert"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-tls-setup
  namespace: lldap
subjects:
- kind: ServiceAccount
  name: istio-tls-setup
  namespace: lldap
roleRef:
  kind: Role
  name: istio-tls-setup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-tls-setup-cross-namespace
subjects:
- kind: ServiceAccount
  name: istio-tls-setup
  namespace: lldap
roleRef:
  kind: ClusterRole
  name: istio-tls-setup-cross-namespace
  apiGroup: rbac.authorization.k8s.io