apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - reflector.yaml
  - metallb.yaml
  - metallb-config.yaml
  - rook-ceph.yaml
  - rook-ceph-cluster.yaml
  - vault.yaml
  - vault-transit-unseal-operator.yaml
  - vault-transit-config.yaml
  - vault-secrets-operator.yaml
  - cert-manager.yaml
  - haproxy-ingress.yaml
  - cloudnative-pg.yaml