apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - vault.yaml
  - vault-transit-unseal-operator.yaml
  - vault-transit-config.yaml
  - external-secrets-operator.yaml
  - external-secrets-config.yaml
  - cert-manager.yaml
  # Temporarily disabled during Istio migration
  # - haproxy-ingress.yaml
  # - haproxy-service.yaml
  - cloudnative-pg.yaml
  - job-vault-pki-sync.yaml
  - nas-vault-eso-token-secret.yaml
  - istio-repository.yaml
  - istio-namespace.yaml
  - istio-base.yaml
  - istio-cni.yaml
  - istio-istiod.yaml
  - istio-ztunnel.yaml
  - istio-gateway.yaml
  - job-istio-tls-setup.yaml