apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cert-manager.yaml
  - job-vault-pki-sync.yaml
  - nas-vault-eso-token-secret.yaml
  - node-feature-discovery.yaml
  # nvidia-device-plugin is deployed via separate kustomization
  # Temporarily disabled - timing out during install
  # - kserve-crds.yaml
  # - kserve.yaml
