apiVersion: v1
kind: Secret
metadata:
  name: nas-vault-eso-token
  namespace: vault
type: Opaque
data:
  # ESO token from NAS Vault for PKI sync
  token: aHZzLkNBRVNJQlBoTnRJYTN3cGlwSmdIQ0tUR3FpdjFVUHpzZ2VCVWFMSE9CLVp1SXMwWkdoNEtIR2gyY3k1cVFuRk9aRzVYU1RWU1RFVmljbEJ0VEZGV2IyUlllbmM=