# Replacement configuration for NAS Vault address
source:
  kind: ConfigMap
  name: global-config
  fieldPath: data.nasVaultAddr
targets:
  - select:
      kind: ConfigMap
      name: vault-config
    fieldPaths:
      - data.vault\.hcl
    options:
      delimiter: "PLACEHOLDER_NAS_VAULT_ADDR"