apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lldap-secret-reader
  namespace: lldap
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["lldap-secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authelia-lldap-secret-reader
  namespace: lldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lldap-secret-reader
subjects:
- kind: ServiceAccount
  name: authelia
  namespace: authelia