---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: postgres-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      
  data:
  - secretKey: username
    remoteRef:
      key: secret/postgres
      property: POSTGRES_USER
  - secretKey: password
    remoteRef:
      key: secret/postgres
      property: POSTGRES_PASSWORD
