apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ovh-credentials-secret.yaml
  - ovh-webhook-helm-repository.yaml
  - ovh-webhook-helm-release.yaml
  - letsencrypt-ovh-webhook-clusterissuer.yaml