apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ovh-credentials
    creationPolicy: Owner
  data:
  - secretKey: applicationKey
    remoteRef:
      key: secret/data/ovh
      property: application_key
  - secretKey: applicationSecret
    remoteRef:
      key: secret/data/ovh
      property: application_secret
  - secretKey: consumerKey
    remoteRef:
      key: secret/data/ovh
      property: consumer_key