apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ovh-credentials
    creationPolicy: Owner
  data:
  - secretKey: applicationKey
    remoteRef:
      key: secret/data/ovh-dns
      property: applicationKey
  - secretKey: applicationSecret
    remoteRef:
      key: secret/data/ovh-dns
      property: applicationSecret
  - secretKey: consumerKey
    remoteRef:
      key: secret/data/ovh-dns
      property: consumerKey