apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  template:
    spec:
      runtimeClassName: nvidia
      containers:
      - name: plex
        resources:
          limits:
            nvidia.com/gpu: 1  # Request 1 GPU
          requests:
            nvidia.com/gpu: 1
        securityContext:
          privileged: true  # Required for GPU access