apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-config
  namespace: plex
spec:
  refreshInterval: 30s
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: plex-config
    creationPolicy: Owner
    deletionPolicy: Retain
  
  # Fetch all keys from plex/config path
  dataFrom:
  - extract:
      key: secret/data/plex/config