apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: plex-config
  namespace: plex
spec:
  type: kv-v2
  mount: secret
  path: plex/config
  destination:
    name: plex-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: plex-auth