apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: plex-vault-populate
  namespace: plex
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  entrypoint: populate-secrets
  serviceAccountName: argo-workflow
  
  templates:
  - name: populate-secrets
    dag:
      tasks:
      - name: wait-vault
        templateRef:
          name: vault-operations
          template: wait-vault-ready
          clusterScope: true
      
      - name: check-secret
        dependencies: [wait-vault]
        templateRef:
          name: vault-operations
          template: check-secret-exists
          clusterScope: true
        arguments:
          parameters:
          - name: secret-path
            value: "secret/plex/config"
      
      - name: create-secret
        dependencies: [check-secret]
        when: "'{{tasks.check-secret.outputs.parameters.exists}}' == 'not-exists'"
        templateRef:
          name: vault-operations
          template: populate-secret
          clusterScope: true
        arguments:
          parameters:
          - name: secret-path
            value: "secret/plex/config"
          - name: secret-data
            value: |
              {
                "claim": "claim-ABC123REPLACEME",
                "timezone": "Europe/Paris"
