# Template for RBAC to read vault-admin-token
# Apps need to patch the name and subject namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: PLACEHOLDER-vault-admin-token-reader  # Apps should patch this
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-admin-token-reader
subjects:
- kind: ServiceAccount
  name: vault-config
  namespace: PLACEHOLDER  # Apps should patch this