apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-PLACEHOLDER
  namespace: PLACEHOLDER
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: smb
  volumeMode: Filesystem