apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//10.10.10.251/k8s-data"
  csi.storage.k8s.io/node-stage-secret-name: "smb-creds"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
  createSubDir: "true"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - vers=3.0
  - file_mode=0777
  - dir_mode=0777