apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - postgres-db-job.yaml
  - postgres-externalsecret.yaml
  - rbac.yaml

configMapGenerator:
  - name: postgres-db-script
    files:
      - create-db.sh