apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yaml
  - vault-config.yaml
  - vault-storage.yaml
  - vault-service.yaml
  - ingress.yaml
  - rbac-vault-config-role.yaml
  - job-vault-init.yaml
  - job-vault-unseal.yaml
  # vault-pvc.yaml is duplicate of vault-storage.yaml

patches:
  - path: patch-velero-backup.yaml
    target:
      kind: StatefulSet
      name: vault