# ConfigMap with transit vault configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-vault-config
  namespace: vault
data:
  config.yaml: |
    transit:
      address: "<path:secret/data/bootstrap/config#nasVaultAddr>"
      mountPath: "transit"
      keyName: "autounseal"
      tlsSkipVerify: true
