apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-admin-token-reader
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["vault-admin-token"]
---
# This ClusterRole allows reading secrets in the vault namespace
# Each app will create a RoleBinding to this Role for their vault-config ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-config-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]