apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-ldap-credentials
  namespace: argocd
spec:
  vaultAuthRef: argocd-auth
  mount: secret
  type: kv-v2
  path: argocd/ldap
  destination:
    create: false
    name: argocd-secret
    transformation:
      excludes:
        - .*
      includes:
        - dex\.ldap\.bindPW
  rolloutRestartTargets:
    - kind: Deployment
      name: argocd-server
    - kind: Deployment
      name: argocd-dex-server
  hmacSecretData: true