apiVersion: v1
data:
  ARGO_CLUSTER_DOMAIN: cluster.local
  ARGO_CLUSTER_NAME: homelab
  ARGO_CONTROL_PLANE_IP: 192.168.1.67
  ARGO_EXTERNAL_DOMAIN: daddyshome.fr
  ARGO_HAPROXY_MOBILE_IP: 192.168.1.81
  ARGO_HARBOR_IP: 192.168.1.90
  ARGO_HARBOR_REGISTRY: 192.168.1.90:5000
  ARGO_HARBOR_REGISTRY_TLS: 192.168.1.90:5443
  ARGO_METALLB_POOL: 192.168.1.80-192.168.1.89
  ARGO_MINIO_BROWSER_REDIRECT_URL: http://192.168.1.42:61901
  ARGO_MINIO_QNAP_URL: http://192.168.1.42:9000
  ARGO_MINIO_SERVER_URL: http://192.168.1.42:61900
  ARGO_NAS_VAULT_ADDR: http://192.168.1.42:61200
  ARGO_QNAP_NAS_IP: 192.168.1.42
  ARGO_VAULT_API_ADDR: http://192.168.1.42:8200
  ARGO_VAULT_CLUSTER_ADDR: http://192.168.1.42:8201
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argocd-envsubst-values
  namespace: argocd
