apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nfs-vault-secret
  namespace: default
spec:
  # Use global VaultAuth
  mount: secret
  path: nfs
  type: kv-v2
  refreshAfter: 1m
  destination:
    create: true
    name: nfscreds
    type: Opaque