apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nfscreds
  namespace: default
spec:
  refreshInterval: 1m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: nfscreds
    creationPolicy: Owner
    deletionPolicy: Retain
  
  # Fetch all keys from nfs path
  dataFrom:
  - extract:
      key: secret/data/nfs