apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nextcloud-admin
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/nextcloud/admin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nextcloud-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/nextcloud/database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-ldap
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nextcloud-ldap
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/nextcloud/ldap