apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-jobs
  namespace: nextcloud
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud-jobs
  namespace: nextcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcloud-jobs
subjects:
- kind: ServiceAccount
  name: nextcloud-jobs
  namespace: nextcloud