apiVersion: batch/v1
kind: Job
metadata:
  name: minio-configure-lifecycle
  namespace: velero
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: configure
        image: minio/mc:RELEASE.2024-08-26T10-49-58Z
        command: ["/scripts/setup-lifecycle.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: minio-lifecycle-script
          defaultMode: 0755