apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - minio-deployment.yaml
  - cronjob-sync-to-qnap.yaml
  - configmap-lifecycle.yaml
  # Argo Workflow
  - argo-workflow-rbac.yaml
  - workflow-configure-lifecycle.yaml
  # - job-configure-lifecycle.yaml  # Replaced by workflow-configure-lifecycle.yaml