apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-setup
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./clusters/homelab/charts/app-setup
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: vault
      namespace: flux-system
    - name: external-secrets
      namespace: flux-system
  values:
    appName: harbor
    vault:
      secrets:
        - path: harbor/admin
          data:
            username: "admin"
            password: "__GENERATE_PASSWORD__"
        - path: harbor/database
          data:
            password: "__GENERATE_PASSWORD__"
        - path: harbor/registry
          data:
            username: "_registry_user"
            password: "__GENERATE_PASSWORD__"
        - path: harbor/registry-user
          data:
            username: "stremio"
            password: "__GENERATE_PASSWORD__"
        - path: harbor/registry-htpasswd
          data:
            htpasswd: ""
        - path: ovh/harbor
          data:
            endpoint: "ovh-eu"
            applicationKey: "REPLACE_WITH_KEY"
            applicationSecret: "REPLACE_WITH_SECRET"
            consumerKey: "REPLACE_WITH_CONSUMER_KEY"
      skipDatabaseCreation: true
    postgres:
      enabled: true
      database: harbor
      username: harbor