apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-apps-superuser
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgres-apps-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/cloudnativepg/postgres-apps
        property: username
    - secretKey: password
      remoteRef:
        key: secret/cloudnativepg/postgres-apps
        property: password