apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

resources:
  - namespace.yaml
  - external-secret.yaml
  - cnpg-cluster.yaml
  - configmap.yaml
  - ca-configmap.yaml
  - ca-certificates-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-simple.yaml