apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-workspace
  namespace: stremio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block