apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry
  namespace: stremio
spec:
  refreshInterval: 30s
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: harbor-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{- $password := .password -}}
          {
            "auths": {
              "harbor-core": {
                "username": "admin",
                "password": "{{ $password }}",
                "auth": "{{ printf "admin:%s" $password | b64enc }}"
              },
              "harbor.daddyshome.fr": {
                "username": "admin",
                "password": "{{ $password }}",
                "auth": "{{ printf "admin:%s" $password | b64enc }}"
              },
              "harbor-registry.harbor.svc.cluster.local:5443": {
                "username": "admin",
                "password": "{{ $password }}",
                "auth": "{{ printf "admin:%s" $password | b64enc }}"
              },
              "PLACEHOLDER_HARBOR_REGISTRY_TLS": {
                "username": "admin",
                "password": "{{ $password }}",
                "auth": "{{ printf "admin:%s" $password | b64enc }}"
              },
              "registry.daddyshome.fr": {
                "username": "admin",
                "password": "{{ $password }}",
                "auth": "{{ printf "admin:%s" $password | b64enc }}"
              }
            }
          }
  
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/harbor/admin
      property: password