apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry-creds
  namespace: stremio
spec:
  refreshInterval: 30s

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: harbor-registry-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{- $username := .username -}}
          {{- $password := .password -}}
          {
            "auths": {
              "PLACEHOLDER_HARBOR_REGISTRY": {
                "username": "{{ $username }}",
                "password": "{{ $password }}",
                "auth": "{{ printf "%s:%s" $username $password | b64enc }}"
              },
              "harbor-registry.harbor.svc.cluster.local:5000": {
                "username": "{{ $username }}",
                "password": "{{ $password }}",
                "auth": "{{ printf "%s:%s" $username $password | b64enc }}"
              },
              "harbor.daddyshome.fr": {
                "username": "{{ $username }}",
                "password": "{{ $password }}",
                "auth": "{{ printf "%s:%s" $username $password | b64enc }}"
              }
            }
          }

  data:
  - secretKey: username
    remoteRef:
      key: secret/data/harbor/registry-user
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/harbor/registry-user
      property: password
