apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-registry-user-vault
  namespace: stremio
spec:
  type: kv-v2
  mount: secret
  path: harbor/registry-user  # Adjust this path to where the secret is stored in Vault
  vaultAuthRef: vault-auth-stremio
  destination:
    name: harbor-registry-creds
    create: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludes:
        - .*
      templates:
        .dockerconfigjson:
          text: |
            {{- $username := .Secrets.username -}}
            {{- $password := .Secrets.password -}}
            {
              "auths": {
                "192.168.1.91:5000": {
                  "username": "{{ $username }}",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "%s:%s" $username $password | b64enc }}"
                },
                "harbor-registry.harbor.svc.cluster.local:5000": {
                  "username": "{{ $username }}",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "%s:%s" $username $password | b64enc }}"
                }
              }
            }
  refreshAfter: 30s