apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-registry-vault
  namespace: stremio
spec:
  type: kv-v2
  mount: secret
  path: harbor/admin
  vaultAuthRef: vault-auth-stremio
  destination:
    name: harbor-registry
    create: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludes:
        - .*
      templates:
        .dockerconfigjson:
          text: |
            {{- $password := .Secrets.password -}}
            {
              "auths": {
                "harbor-core": {
                  "username": "admin",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "admin:%s" $password | b64enc }}"
                },
                "harbor.daddyshome.fr": {
                  "username": "admin",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "admin:%s" $password | b64enc }}"
                },
                "harbor-registry.harbor.svc.cluster.local:5443": {
                  "username": "admin",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "admin:%s" $password | b64enc }}"
                },
                "192.168.1.90:5443": {
                  "username": "admin",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "admin:%s" $password | b64enc }}"
                },
                "registry.daddyshome.fr": {
                  "username": "admin",
                  "password": "{{ $password }}",
                  "auth": "{{ printf "admin:%s" $password | b64enc }}"
                }
              }
            }
  refreshAfter: 30s
