apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-web
  namespace: stremio
spec:
  template:
    spec:
      initContainers:
      - name: copy-build
        image: harbor-core.harbor.svc.cluster.local/library/stremio-web:latest