apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stremio-web-data
  namespace: stremio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block