apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stremio-config
  namespace: stremio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stremio-media
  namespace: stremio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 100Gi