apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: stremio
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: stremio
    serviceAccount: default
  vaultConnectionRef: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: stremio
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true