name: haproxy-ingress
project: core
namespace: haproxy-controller
path: manifests/core/haproxy-ingress
autoSync: "false"  # Ingress controller changes can lock out access
prune: "false"     # Keep ingress resources safe
syncWave: "-8"