apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: client-ca-cert
  namespace: haproxy-controller
spec:
  type: kv-v2
  mount: secret
  path: client-ca
  destination:
    name: client-ca-cert
    create: true
    overwrite: true
    type: kubernetes.io/tls
    transformation:
      templates:
        tls.crt:
          text: |
            {{- get .Secrets "ca.crt" -}}
        tls.key:
          text: |
            {{- get .Secrets "ca.key" -}}
  vaultAuthRef: vault-auth