apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - namespace.yaml
  - service-account.yaml
  - external-secrets.yaml
  # - harbor-ip-pool.yaml    # No longer needed with internal DNS
  # - harbor-registry-lb.yaml # No longer needed with internal DNS
  - ingress.yaml
  - harbor-helmrelease.yaml