apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - namespace.yaml
  - service-account.yaml
  # - external-secrets.yaml  # Replaced with generated secrets
  - password-generators.yaml
  - external-secrets-generated.yaml
  - ingress.yaml
  - harbor-helmrelease.yaml
