apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-local
  resources:
    requests:
      storage: 10Gi