apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  type: kv-v2
  mount: secret
  path: harbor/admin
  destination:
    name: harbor-admin-secret
    create: true
    transformation:
      templates:
        harborAdminPassword:
          text: '{{ .Secrets.password }}'
  refreshAfter: 30s
  vaultAuthRef: harbor-auth