apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-database
  namespace: harbor
spec:
  vaultAuthRef: harbor-auth
  mount: secret
  type: kv-v2
  path: harbor/database
  destination:
    create: true
    name: harbor-database-secret
    transformation:
      templates:
        db-password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 30s
  hmacSecretData: true