apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  vaultAuthRef: harbor-auth
  mount: secret
  type: kv-v2
  path: harbor/registry
  destination:
    create: true
    name: harbor-registry-secret
    transformation:
      templates:
        REGISTRY_HTPASSWD:
          text: '{{ .Secrets.htpasswd }}'
        REGISTRY_HTTP_SECRET:
          text: '{{ .Secrets.http_secret }}'
  refreshAfter: 30s
  hmacSecretData: true