apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  type: kv-v2
  mount: secret
  path: harbor/registry
  destination:
    name: harbor-registry-secret
    create: true
    transformation:
      templates:
        username:
          text: 'harbor_registry_user'
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 30s
  vaultAuthRef: harbor-auth