apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  # App-specific resources
  - namespace.yaml
  - harbor-serviceaccount.yaml
  - harbor-admin-eso.yaml  # ESO resource for admin credentials
  - harbor-database-eso.yaml  # ESO resource for database credentials
  - harbor-registry-eso.yaml  # ESO resource for registry credentials
  - ovh-credentials-eso.yaml  # ESO resource for OVH credentials
  - harbor-vault-populate-job.yaml
  - harbor-registry-config-job.yaml
  - harbor-ingress.yaml
  - harbor-ip-pool.yaml
  - harbor-registry-lb.yaml

helmCharts:
- name: harbor
  chartHome: ./charts/harbor-26.8.0/harbor
  releaseName: harbor
  namespace: harbor
  valuesFile: values-bitnami-tls.yaml