# Bitnami Harbor values
expose:
  type: proxy
  proxy:
    httpPort: 80
    httpsPort: 443
# External URL
externalURL: http://192.168.1.90

# Disable internal TLS when using ingress
internalTLS:
  enabled: false

# Configure nginx proxy
nginx:
  enabled: true
  tls:
    enabled: false

# Admin password from existing secret
adminPassword: ""
existingAdminPasswordSecret: harbor-admin-secret

# Use external Redis
redis:
  enabled: false
externalRedis:
  host: redis-standalone.ot-operators.svc.cluster.local
  port: 6379

# Persistence
persistence:
  enabled: true
  storageClass: "rook-ceph-block"

# Use external PostgreSQL
postgresql:
  enabled: false

# External database configuration
externalDatabase:
  host: postgres-apps-rw.postgres.svc.cluster.local
  port: 5432
  user: harbor
  password: HarborDB123
  sslmode: disable
  coreDatabase: core

# Core configuration
core:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

# Registry configuration
registry:
  replicas: 1
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 50Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1000m
  credentials:
    username: harbor_registry_user
    password: "33V4wUaUxgEC2cFEqENfkv"
    # generated with: htpasswd -nbB <username> <password>
    htpasswd: |
      harbor_registry_user:$2y$05$LT7ytH9EJNDqiGaoupVQrudKtXRNhPRl92NmC7vL7k2ngnnH.RjaK

# Jobservice configuration
jobservice:
  replicas: 1
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

# Portal configuration
portal:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

# Trivy configuration
trivy:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 5Gi

# Metrics
metrics:
  enabled: true
