#!/bin/bash
set -euo pipefail

# Script to convert .env file to global-config.yaml and push to homelab-values repo

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Check if .env file exists
if [ ! -f "${ROOT_DIR}/.env" ]; then
    echo "Error: .env file not found at ${ROOT_DIR}/.env"
    exit 1
fi

# Check if required environment variables are provided
if [ -z "${GITHUB_HOMELAB_VALUES_TOKEN:-}" ]; then
    echo "Error: GITHUB_HOMELAB_VALUES_TOKEN environment variable is not set"
    exit 1
fi

if [ -z "${GITHUB_HOMELAB_VALUES_REPO:-}" ]; then
    echo "Error: GITHUB_HOMELAB_VALUES_REPO environment variable is not set"
    exit 1
fi

# Check if global-config.yaml exists
if [ ! -f "${ROOT_DIR}/global-config.yaml" ]; then
    echo "Error: global-config.yaml not found. Please run generate-config task first."
    exit 1
fi

echo "Using existing global-config.yaml"

# Clone or update homelab-values repo
TEMP_DIR=$(mktemp -d)
trap "rm -rf ${TEMP_DIR}" EXIT

echo "Cloning homelab-values repository..."
# Extract username and repo from the URL
REPO_URL="${GITHUB_HOMELAB_VALUES_REPO}"
# Remove https:// prefix
REPO_PATH="${REPO_URL#https://}"
# Extract GitHub username and repo name
GITHUB_USER=$(echo "${REPO_PATH}" | cut -d'/' -f2)
GITHUB_REPO=$(echo "${REPO_PATH}" | cut -d'/' -f3)

git clone "https://${GITHUB_HOMELAB_VALUES_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git" "${TEMP_DIR}/homelab-values"

# Copy the global-config.yaml to the repo
cp "${ROOT_DIR}/global-config.yaml" "${TEMP_DIR}/homelab-values/global-config.yaml"

# Commit and push if there are changes
cd "${TEMP_DIR}/homelab-values"
git config user.email "terraform@homelab.local"
git config user.name "Terraform Automation"

# Set the remote URL with token for push
git remote set-url origin "https://${GITHUB_HOMELAB_VALUES_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git"

if ! git diff --quiet; then
    git add global-config.yaml
    git commit -m "Update global-config.yaml from .env

Generated by sync-global-config.sh
Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    
    echo "Pushing changes to homelab-values repository..."
    git push origin main
    echo "Successfully pushed global-config.yaml to homelab-values repository"
else
    echo "No changes detected in global-config.yaml"
fi

# Clean up local global-config.yaml after sync
rm -f "${ROOT_DIR}/global-config.yaml"

echo "Sync completed successfully"