#!/bin/bash
set -euo pipefail

# Script to convert .env file to global-config.yaml and push to homelab-values repo

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Check if .env file exists
if [ ! -f "${ROOT_DIR}/.env" ]; then
    echo "Error: .env file not found at ${ROOT_DIR}/.env"
    exit 1
fi

# Check if GitHub token is provided
if [ -z "${GITHUB_HOMELAB_VALUES_TOKEN:-}" ]; then
    echo "Error: GITHUB_HOMELAB_VALUES_TOKEN environment variable is not set"
    exit 1
fi

# Source the .env file
set -a
source "${ROOT_DIR}/.env"
set +a

# Create global-config.yaml content
cat > "${ROOT_DIR}/global-config.yaml" << EOF
# Global configuration values for all applications
# This file is generated from .env - DO NOT EDIT MANUALLY
# Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Domain configuration
defaultExternalDomain: ${EXTERNAL_DOMAIN}
clusterDomain: ${CLUSTER_DOMAIN}

# Infrastructure IPs and URLs
controlPlaneIP: ${CONTROL_PLANE_IP}
worker1IP: ${WORKER_1_IP}
worker2IP: ${WORKER_2_IP}
metallbPool: ${METALLB_POOL}
haproxyMobileIP: ${HAPROXY_MOBILE_IP}
harborIP: ${HARBOR_IP}
harborRegistry: ${HARBOR_REGISTRY}
harborRegistryTLS: ${HARBOR_REGISTRY_TLS}

# NAS configuration
qnapNasIP: ${QNAP_NAS_IP}
nasVaultAddr: ${NAS_VAULT_ADDR}
minioQnapUrl: ${MINIO_QNAP_URL}

# MinIO browser configuration
minioBrowserRedirectUrl: ${MINIO_BROWSER_REDIRECT_URL}
minioServerUrl: ${MINIO_SERVER_URL}

# Vault API addresses
vaultApiAddr: ${VAULT_API_ADDR}
vaultClusterAddr: ${VAULT_CLUSTER_ADDR}
EOF

echo "Generated global-config.yaml"

# Clone or update homelab-values repo
TEMP_DIR=$(mktemp -d)
trap "rm -rf ${TEMP_DIR}" EXIT

echo "Cloning homelab-values repository..."
git clone https://fredericrous:${GITHUB_HOMELAB_VALUES_TOKEN}@github.com/fredericrous/homelab-values.git "${TEMP_DIR}/homelab-values"

# Copy the global-config.yaml to the repo
cp "${ROOT_DIR}/global-config.yaml" "${TEMP_DIR}/homelab-values/global-config.yaml"

# Commit and push if there are changes
cd "${TEMP_DIR}/homelab-values"
git config user.email "terraform@homelab.local"
git config user.name "Terraform Automation"

if ! git diff --quiet; then
    git add global-config.yaml
    git commit -m "Update global-config.yaml from .env

Generated by sync-global-config.sh
Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    
    echo "Pushing changes to homelab-values repository..."
    git push origin main
    echo "Successfully pushed global-config.yaml to homelab-values repository"
else
    echo "No changes detected in global-config.yaml"
fi

# Keep a copy for terraform to use temporarily
cp "${ROOT_DIR}/global-config.yaml" "${ROOT_DIR}/.global-config.yaml.tmp"

# Clean up local global-config.yaml
rm -f "${ROOT_DIR}/global-config.yaml"

echo "Sync completed successfully"