apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secrets
  namespace: lldap
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: lldap-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: lldap
        property: LLDAP_JWT_SECRET
    - secretKey: ldap_user_pass
      remoteRef:
        key: lldap
        property: LLDAP_LDAP_USER_PASS