apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: lldap-config
  namespace: lldap
spec:
  vaultAuthRef: lldap
  type: kv-v2
  mount: secret
  path: lldap/config
  destination:
    name: lldap-config
    create: true
    type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: lldap-jwt-secret
  namespace: lldap
spec:
  vaultAuthRef: lldap
  type: kv-v2
  mount: secret
  path: lldap/jwt
  destination:
    name: lldap-jwt-secret
    create: true
    type: Opaque