apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: lldap
  namespace: lldap
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: lldap
    serviceAccount: lldap