apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: lldap-secrets
  namespace: lldap
spec:
  vaultAuthRef: lldap
  type: kv-v2
  mount: secret
  path: lldap
  destination:
    name: lldap-secrets
    create: true
    type: Opaque
    transformation:
      templates:
        jwt_secret:
          text: '{{ .Secrets.LLDAP_JWT_SECRET }}'
        ldap_user_pass:
          text: '{{ .Secrets.LLDAP_LDAP_USER_PASS }}'