name: argocd-config
project: core
namespace: argocd
path: manifests/core/argocd-config
syncWave: "-20"  # After ArgoCD itself
createNamespace: "false"  # argocd namespace already exists
serverSideApply: "true"