# Secret containing AVP configuration
# These values will be replaced by ArgoCD vault plugin from NAS vault
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-config
  namespace: argocd
type: Opaque
stringData:
  AVP_VAULT_ADDR: <path:secret/data/bootstrap#nas-vault-addr>
  AVP_TOKEN: <path:secret/data/bootstrap#nas-vault-token>