apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-envsubst-values-external
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-envsubst-values-external
    creationPolicy: Owner
    template:
      data:
        values: |
          {{- range $k, $v := .data }}
          {{ $k }}={{ $v }}
          {{- end }}
  dataFrom:
    - extract:
        key: secret/argocd/env-values