apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwebui-tls
  namespace: openwebui
spec:
  secretName: openwebui-tls
  issuerRef:
    name: letsencrypt-ovh-webhook
    kind: ClusterIssuer
  dnsNames:
  - ai.${PUBLIC_DOMAIN}