apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openwebui

resources:
  - namespace.yaml
  - service-account.yaml
  - certificate.yaml
  - istio-system-gateway.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - virtualservice.yaml