apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: smbcreds
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: smb
  destination:
    name: smbcreds
    create: true
    type: Opaque
  refreshAfter: 30s
  vaultAuthRef: default-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default-auth
  namespace: default
spec:
  kubernetes:
    role: default
    serviceAccount: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default