apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: default
  namespace: vault-secrets-operator
spec:
  defaultAuthMethod: kubernetes
  defaultMount: kubernetes
  vaultConnectionRef: vault-connection
  allowedNamespaces:
    - "*"
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: vault-secrets-operator-controller-manager
    namespace: vault-secrets-operator