# VSO resource to pull OVH credentials from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ovh-credentials
  namespace: authelia
spec:
  type: kv-v2
  mount: secret
  path: ovh-dns
  destination:
    name: ovh-credentials
    create: true
    type: Opaque
  refreshAfter: 30s
  vaultAuthRef: authelia