apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haproxy-controller

secretGenerator:
- name: client-ca-cert
  files:
  - tls.crt=ca/ca.crt
  options:
    disableNameSuffixHash: true
