apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy-default-deny.yaml
  - network-policy-allow-ingress.yaml
  - network-policy-allow-dns.yaml
  - network-policy-allow-vault.yaml

patches:
  - path: security-context-patch.yaml
    target:
      kind: Deployment
  - path: security-context-patch.yaml
    target:
      kind: StatefulSet