---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: authelia-gateway
  namespace: istio-ingress
  annotations:
    gateway.istio.io/tls-terminate-mode: MUTUAL
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "auth.daddyshome.fr"
    port: 80
    protocol: HTTP
  - name: https
    hostname: "auth.daddyshome.fr" 
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: authelia-tls
        namespace: authelia
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authelia-redirect
  namespace: authelia
spec:
  hosts:
  - auth.daddyshome.fr
  gateways:
  - authelia-gateway
  http:
  # HTTP to HTTPS redirect for port 80
  - match:
    - port: 80
    redirect:
      scheme: https
      redirectCode: 301
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authelia-https
  namespace: authelia
spec:
  hosts:
  - auth.daddyshome.fr
  gateways:
  - authelia-gateway
  http:
  # HTTPS traffic to service (port 443)
  - match:
    - port: 443
    route:
    - destination:
        host: authelia
        port:
          number: 80