apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cert-manager-ovh-credentials
  namespace: flux-system
spec:
  type: kv-v2
  mount: secret
  path: ovh-dns
  destination:
    name: cert-manager-env-config
    create: true
    transformation:
      excludes:
        - .*
      templates:
        CERT_MANAGER_OVH_APPLICATION_KEY:
          text: |
            {{- get .Secrets "applicationKey" -}}
        CERT_MANAGER_OVH_CONSUMER_KEY:
          text: |
            {{- get .Secrets "consumerKey" -}}
  vaultAuthRef: vault-auth-flux-system