apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-ca-cert
  namespace: haproxy-ingress
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: client-ca-cert
    creationPolicy: Owner
  data:
  - secretKey: ca.crt
    remoteRef:
      key: secret/data/pki/ca
      property: certificate
  - secretKey: ca.key
    remoteRef:
      key: secret/data/pki/ca
      property: private_key