apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cluster-config.yaml
  - kyverno
  - cert-manager-setup.yaml
  - cert-manager-env-config.yaml
  - cert-manager
  - client-ca-externalsecret.yaml
  - lldap-istio-gateway.yaml
  - authelia-istio-gateway.yaml