---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: postgres-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authelia,nextcloud,vikunja,vaultwarden"  # Add more as needed
      
  data:
  - secretKey: username
    remoteRef:
      key: secret/postgres
      property: POSTGRES_USER
  - secretKey: password
    remoteRef:
      key: secret/postgres
      property: POSTGRES_PASSWORD