apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-flux-system
  namespace: flux-system
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: flux-system
    serviceAccount: default
    audiences:
      - vault