apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nextcloud-vault-secret
  namespace: nextcloud
spec:
  vaultAuthRef: nextcloud-auth
  mount: secret
  path: nextcloud
  type: kv-v2
  refreshAfter: 1m
  destination:
    create: true
    name: nextcloud-secrets
    type: Opaque
    overwrite: true