apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: 1m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: nextcloud-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  
  # Fetch all keys from nextcloud path
  dataFrom:
  - extract:
      key: secret/data/nextcloud