apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  template:
    spec:
      # Add runtime class for GPU support (for video transcoding)
      runtimeClassName: nvidia
      containers:
      - name: nextcloud
        resources:
          limits:
            nvidia.com/gpu: 1