apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-superuser-vault
  namespace: nextcloud
spec:
  type: kv-v2
  mount: secret
  path: postgres/superuser
  vaultAuthRef: vault-auth-nextcloud
  destination:
    name: postgres-superuser-secret
    create: true
    type: Opaque
    transformation:
      excludes:
        - .*
      templates:
        password:
          text: "{{ .Secrets.password }}"
  refreshAfter: 30s