apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser-secret
  namespace: nextcloud
spec:
  refreshInterval: 30m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: postgres-superuser-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        password: '{{ .password | toString }}'
  
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/postgres/superuser
      property: password