apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-media
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-vms
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-vms