apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubernetes-reflector

resources:
  - namespace.yaml
  - https://github.com/emberstack/kubernetes-reflector/releases/download/v7.1.262/reflector.yaml

# Optional: Install via Helm instead
# helmCharts:
# - name: reflector
#   repo: https://emberstack.github.io/helm-charts
#   version: 7.1.262
#   namespace: kubernetes-reflector
#   releaseName: reflector
#   valuesInline:
#     resources:
#       requests:
#         cpu: 10m
#         memory: 64Mi
#       limits:
#         memory: 128Mi