apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 10m
  timeout: 2m
  wait: true
  path: ./clusters/homelab/infrastructure/configs/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system