apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-ovh-setup-credentials
  namespace: cert-manager
type: Opaque
stringData:
  applicationKey: "a4598a81b100e759"
  applicationSecret: "2066396e3b624e34d4f1a3d009ca0139"
  consumerKey: "cb8d03d3d3a2de55f9df196190022425"