apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls-certificate
  namespace: plex
spec:
  secretName: plex-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - plex.daddyshome.fr